version: '3'
services:
  web:
    build: .
    ports:
      - "5001:80"
    depends_on:
      rabbit:
        condition: service_healthy
  mongo:
     image: "mongo"
     healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:27017"]
        interval: 30s
        timeout: 10s
        retries: 5